manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware-infused-kim
      revision: aa-my-customizations-z3
      import: app/west.yml
  self:
    path: config
